language: node_js
node_js:
  - "6.10"
  - "4.3"
  - "10"
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
- pip install --user awscli
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test:coverage-travis
after_success:
  - npm run semantic-release
  - make update
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
