sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'stable'
script:
  - npm run lint
  - npm run test:coverage
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
